sudo: required
services:
  - docker
language: python
python:
  - "2.7"
  - "3.5"
install:
  - "pip install -r requirements.txt"
script:
  - ansible-playbook deploy.yml --syntax-check
  - ansible-playbook deploy.yml
