sudo: required
services:
  - docker
language: python
python:
  - "2.7"
install:
  - "pip install -r requirements.txt"
  - docker build -t test_container .
  - docker run -d -p 127.0.0.1:5000:5000 --name test_container test_container
script:
  - pytest
  - ansible-playbook deploy.yml --syntax-check
  - python manage.py initdb
  - python roles/deploy/files/validate.py
