sudo: required
services:
  - docker
language: python
python:
  - "2.7"
  - "3.5"
install:
  - "pip install -r requirements.txt"
  - "pip install pytest-flask"
  - "pip install requests"
  - docker build -t test_container .
  - docker run -d -p 127.0.0.1:80:80 --name test_container test_container
script:
  - pytest
  - ansible-playbook deploy.yml --syntax-check
  - python roles/deploy/files/validate.py
